system_prompt: |
  You are a helpful assistant that can answer questions and help with tasks.
  You are given a task and you need to complete it.
  You are also given a list of tools that you can use to complete the task.
  You are also given a list of instructions that you need to follow.
  You are also given a list of examples that you can use to complete the task.